### PR TITLE
Update to bing ads api v10

### PR DESCRIPTION
**Pull request by alexcavalli**
http://jira.office.vertive.com/browse/VUL-7382

### CODE REVIEW

**Comment by knodi** [comment]
@alexcavalli , I think you need to freeze the rack version in the gemspec, see https://github.com/info-sys/tracking/commit/efffe34e2b975f49f5d07056804fb1a066723fa0

**Comment by alexcavalli** [comment]
@knodi Switch to MRI.

We can freeze gems in places that depend on this. I don't see a reason to lock it to a lower version, it seems to work just fine on newer versions as long as you're on a ruby those newer version support.

**Comment by alexcavalli** [comment]
@knodi You may also notice that reporting specs are failing. I couldn't figure out the reason behind that, and reporting is working in production (technically nothing changed with that api, it remains on v9). Was getting 500 errors from the server side. :shrug:

**Comment by knodi** [comment]
LGTM.

**Pull request merged**
